### ISSUE TITLE
MolMeDB annotator duplicate metabolite row merging

### ISSUE THREAD

**Issue by DominikMartinat** [BioDataFuse/pyBiodatafuse#54]
I have reworked merging for MolMeDB annotator with transporter genes and more importantlz i did same for metabolites as there are some one-to-manz mappings of identifier to InChIKey.

However there is an issue with KEGG C06861 and PubChem compound 107927 where each maps to InChIKeys of very different molecules, both of which have record in MolMeDB. I am pretty sure it is erroneous mapping and the merging works for all other relevant identifiers. Can I make PR with code as is, or should I solve the issue with identifiers first? @tabbassidaloii @YojanaGadiya

**Comment by tabbassidaloii** [comment]
If I understood correctly, the issue is not with the codes but with the database itself, is it true?  
Would the users get an output for these two examples as well? (I assume it will be multiple rows for each?)
If that is the case you can consider updating the codes, but please do the required follow-up to solve the issue with them.

**Comment by DominikMartinat** [comment]
The issue is on the part of BridgeDB mapping. Users would get output with multiple rows now, nut i think it would be problematic with combining results of multiple annotators. So I will update the code now and solve the mapping with BridgeDB.

**Comment by tabbassidaloii** [comment]
I see now.
Okay, thank you!

**Comment by tabbassidaloii** [comment]
@DominikMartinat 
is it solved?

**Comment by DominikMartinat** [comment]
yes
